# This is a declarative approach to describe a Job type Kubernetes
# workload.   Since this is YAML, the indentation is very important
apiVersion: batch/v1
kind: Job         # We are testing the Job resource type
metadata:
  name: zookeeper-job  # A name must be given to the Job type in the metadata section
spec:                     # This is the specification where we can even put the number of replicas
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: zookeeper        # some label to give to this pod (see the matching label above)
    spec:                 # actual specification
      nodeSelector:
        kubernetes.io/hostname: kubemaster
      containers:
      - name: zookeeper       # this is going to be used for DNS name
        # Change the IP address to where you are running this
        image: 129.114.26.34:5000/dockerimage1   # this is the image in registry accessible
                                             # from all our workers
        imagePullPolicy: Always  # This forces the node to pull the image
        command: ["./kafka_2.13-2.7.0/bin/zookeeper-server-start.sh"]
        args: ["./kafka_2.13-2.7.0/config/zookeeper.properties"]
      restartPolicy: Never  # we ask Kubernetes not to restart
