---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2016
# Modified: Fall 2018
# Modified: Fall 2020
#
# In this playbook, we will show how to remove an installed package via
# the aptitude module
#
 
                     # the task to be performed

- name: Installing prereqs
  apt: 
    name: [apt-transport-https, gnupg2, curl]
    update_cache: yes
    
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: coppying a file to kubernetes.list
  shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" \
   | sudo tee -a /etc/apt/sources.list.d/kubernetes.list  
     
- name: Installing
  apt: 
    name: [kubeadm, kubelet, kubectl, kubernetes-cni]
    update_cache: yes
    
# - name: Configure node ip
    # lineinfile:
      # path: /etc/default/kubelet
      # line: KUBELET_EXTRA_ARGS=--node-ip=129.

# - name: Restart kubelet
  # service:
    # name: kubelet
    # daemon_reload: yes
    # state: restarted
...

