---
- name: "Create VM2"
  openstack.cloud.server:
    cloud: 
    auth:
      auth_url: https://kvm.tacc.chameleoncloud.org:5000/v3
    state: present
    name: martin_vm
    image: 87ddd9ba-e74c-4499-9b65-c9a92fd14edd
    flavor: m1.medium
    key_name: martin_key
    security_groups: ENABLE_COUCHDB_PORT,ENABLE_HTTP_HTTPS,ENABLE_KAFKA_COUCHDB,ENABLE_SSH,667273fd-a67a-4ca2-8a68-3088220e6374,7e09e9fd-4971-49bb-bd55-9aa2fa149b16
    nics: net-id=4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
    floating_ips: 129.114.26.34
    availability_zone: nova

- name: "Create VM3"
  openstack.cloud.server:
    cloud: 
    auth:
      auth_url: https://kvm.tacc.chameleoncloud.org:5000/v3
    state: present
    name: harriott_vm
    image: 87ddd9ba-e74c-4499-9b65-c9a92fd14edd
    flavor: m1.small
    key_name: kahero_key
    security_groups: ENABLE_COUCHDB_PORT,ENABLE_HTTP_HTTPS,ENABLE_KAFKA_COUCHDB,ENABLE_SSH,667273fd-a67a-4ca2-8a68-3088220e6374,7e09e9fd-4971-49bb-bd55-9aa2fa149b16
    nics: net-id=4b484898-92b4-4a4b-9c5d-7d55bd72f1ee
    floating_ips: 129.114.26.247
    availability_zone: nova
    
- name: Pause for 30 seconds
  pause:
    seconds: 30
...