---
- name: Reset the Kubernetes cluster using kubeadm
  shell: kubeadm reset -f

- name: Deleteing the ~/.kube directory
  file:
    name: root/.kube
    state: absent

- name: Deleteing the net.d/ directory
  file:
      name: /etc/cni/net.d/
      state: absent

...

