---

- name: Installing prereqs
  apt: 
    name: [apt-transport-https, gnupg2, curl]
    update_cache: yes
    
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

#Might need to do this:
#- name: Delete kubernetes.list
  #ansible.builtin.shell: rm /etc/apt/sources.list.d/kubernetes.list
  
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
      
- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list 
     
- name: Installing
  apt: 
    name: [kubeadm, kubelet, kubectl, kubernetes-cni]
    update_cache: yes
    
# - name: Configure node ip
    # lineinfile:
      # path: /etc/default/kubelet
      # line: KUBELET_EXTRA_ARGS=--node-ip=129.

# - name: Restart kubelet
  # service:
    # name: kubelet
    # daemon_reload: yes
    # state: restarted
...

