---
  
# - name: "Play 1: Download Kafka TGZ"
  # hosts: MyLocalVMs
  # become: yes
  # remote_user: vagrant
  # collections:
   # - ansible-base
   # - openstack.cloud.collection
 
  # tasks:
  # - import_tasks: ./playbook_install_kafka_tgz.yml


- name: "Play 2: Create VMs on Chameleon"
  hosts: MyLocalVMs
  remote_user: vagrant
  collections:
   - ansible-base
   - openstack.cloud.collection
 
  tasks:
  - import_tasks: ./playbook_create_cloud_vm.yml

- name: "Play 3: Copy Dockerfile and K8S YAMLs from Vagrant Machine to VM2"
  hosts: VM2
  remote_user: cc
  collections:
   - ansible-base
   - openstack.cloud.collection
 
  tasks:
  - import_tasks: ./playbook_set_up_docker_k8s.yml
  
- name: "Play 4: Install Kafka on VM2"
  hosts: VM2
  remote_user: cc
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  gather_facts: yes
  become: yes
  
  tasks:
  - import_tasks: ./playbook_install_app_on_cloud_vm.yml

- name: "Play 4: Set UFW Limits"
  hosts: MyChameleonVMs
  remote_user: cc
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  gather_facts: yes
  become: yes
  
  tasks:
  - import_tasks: ./playbook_set_ufw_limits.yml
  
- name: "Play 4: Install Docker"
  hosts: MyChameleonVMs
  remote_user: cc
  become: yes
  gather_facts: yes
  collections:
  - ansible-base
  
  tasks:
  - import_tasks: ./playbook_Docker_Install.yml

- name: "Play 5: Create Private Registry for Docker Images"
  hosts: VM2
  remote_user: cc
  become: yes
  gather_facts: yes
  collections:
  - ansible-base
  
  tasks:
  - import_tasks: ./playbook_create_private_registry.yml 

- name: "Play 6: Adding Registry Information"
  hosts: MyChameleonVMs
  remote_user: cc
  become: yes
  gather_facts: yes
  collections:
  - ansible-base
  
  tasks:
  - import_tasks: ./playbook_add_registry_information.yml  
  
- name: "Play 7: Install Kubernetes"
  hosts: MyChameleonVMs
  remote_user: cc
  become: yes
  gather_facts: yes
  collections:
  - ansible-base
  
  tasks:
  - import_tasks: ./playbook_Kubernetes_Install.yml    

- name: "Play 8: Create the Kube cluster"
  hosts: VM2
  remote_user: cc
  become: yes
  tasks:
  - include_tasks: ./playbook_start_k8s_Cluster.yml

- name: "Play 9: Taint the master for Kube"
  hosts: VM2
  remote_user: cc
  become: yes
  tasks: 
  - include_tasks: ./playbook_taint_master.yml

- name: "Play 10: Joining VM3 to the cluster"
  hosts: VM3
  remote_user: cc
  become: yes
  tasks:
  - include_tasks: ./playbook_join_VM3.yml  
  
- name: "Play 11: Create Docker Image"
  hosts: VM2
  remote_user: cc
  become: yes
  tasks:
  - include_tasks: ./playbook_create_dockerimage.yml
  
- name: "Play 13: start couchdb docker"
  hosts: VM3
  remote_user: cc
  become: yes
  tasks:
  - include_tasks: ./playbook_start_couchdb_docker.yml  

- name: "Play 14: Deploy k8s"
  hosts: VM2
  remote_user: cc
  become: yes
  tasks:
  - include_tasks: ./playbook_deploy_k8s.yml

# - name: "Play 15: Run Producer"
  # hosts: MyLocalVMs
  # remote_user: cc
  # become: yes
  # tasks:
  # - include_tasks: ./playbook_run_producer.yml 
    
  
# - name: "Play 3a: Edit Server Properties on VM2"
  # hosts: VM2
  # remote_user: cc
  # collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    # - openstack.cloud
  # gather_facts: yes
  # become: yes
  
  # tasks:
  # - include_tasks: ./playbook_edit_server_properties1.yml
  
# - name: "Play 3b: Edit Server Properties on VM3"
  # hosts: VM3
  # remote_user: cc
  # collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    # - openstack.cloud
  # gather_facts: yes
  # become: yes
  
  # tasks:
  # - include_tasks: ./playbook_edit_server_properties2.yml

# - name: "Play 4: Copy Consumer Code over to Cloud VM3"
  # hosts: VM3
  # remote_user: cc
  # collections: ansible-base
  
  # tasks:
  # - import_tasks: ./playbook_copy_consumer_vm2.yml
  
# - name: "Play 4: Copy local.ini to VM3"
  # hosts: VM3
  # remote_user: cc
  # collections: ansible-base
  
  # tasks:
  # - import_tasks: ./playbook_copy_localini_vm3.yml

# - name: "Play 5: Install CouchDB"
  # hosts: VM3
  # remote_user: cc
  # become: yes
  # gather_facts: yes
  # collections:
   # - ansible-base
   
  # tasks:
  # - import_tasks: ./playbook_CouchDB_Install.yml


# - name: "Play 6: Start Zookeeper on VM2"
  # hosts: VM2
  # remote_user: cc
  # collections: ansible-base
  # become: yes
  # tasks:
  # - import_tasks: ./playbook_install_java.yml
  # - import_tasks: ./playbook_start_zookeeper.yml
  
# - name: "Play 7: Start Kafka Brokers"
  # hosts: MyChameleonVMs
  # remote_user: cc
  # become: yes
  # tasks:
  # - include_tasks: ./playbook_start_kafka_server.yml

# - name: "Play 8: Run Consumer Code"
  # hosts: VM3
  # remote_user: cc
  # tasks: 
  # - include_tasks: ./playbook_run_consumer.yml

# - name: "Play 9: Delete Cloud VMs"
  # hosts: MyLocalVMs
  # remote_user: cc
  # tasks: 
  # - include_tasks: ./playbook_remove_cloud_VMs.yml
  
# - name: "Copy the Code folder over to both VMs"
  # hosts: MyChameleonVMs
  # remote_user: cc
  # tasks:
  # - include_tasks: ./playbook_copy_code.yml

#- name: Remove the Kube cluster
#  hosts: MyChameleonVMs
#  remote_user: cc
#  become: yes
#  tasks:
#  - include_tasks: ./playbook_remove_k8s_Cluster.yml


...

